household_power_consumption <- read.csv("/media/asier/Vault1/Cursos/Coursera - Exploratory Data Analysis/household_power_consumption.txt", sep=";")
x <- household_power_consumption[household_power_consumption$Date %in% c('1/2/2007','2/2/2007'),]
weekdays <- strptime(paste(x$Date, x$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
x$Global_active_power <- as.numeric(x$Global_active_power)
x$Global_reactive_power <- as.numeric(x$Global_reactive_power)
x$Voltage <- as.numeric(x$Voltage)
x$Sub_metering_1 <- as.numeric(x$Sub_metering_1)
x$Sub_metering_2 <- as.numeric(x$Sub_metering_2)
x$Sub_metering_3 <- as.numeric(x$Sub_metering_3)
png(filename='plot4.png',width=480,height=480)
par(mfrow = c(2, 2)) 
plot(weekdays, x$Global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(weekdays, x$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(weekdays, x$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(weekdays, x$Sub_metering_2, type="l", col="red")
lines(weekdays, x$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(weekdays, x$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
